# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14784638dcc15d6c82265b44b715da785c727586d4520b3738e67f1add52134e8ec0a8e273b46bb2fcc43460cdf03f60c29b0134576f3a2239a6426a3a40ec4d

test:
  secret_key_base: 5279fe19b1d7985f8aa5563830d84c72f7d286e4969c705e5174afc50bdb08499be95becc4a5117c1c48cf7dcf900e6ad4d8e1b2aa6088ebf32cd71811b6b162

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
